config/routes.rb
Rails.application.routes.draw do
  root to: "pages#welcome"
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  resources :entries, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  default_scope { order(created_at: :desc) }
  validates :location, :note, :user_id, presence: true

  has_one_attached :photo

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
    :validatable, :confirmable, :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :entries

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data["email"]).first
    unless user
      user = User.new(name: data["name"],
        email: data["email"],
        password: Devise.friendly_token[0, 20])
      user.skip_confirmation!
      user.save
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @entries = current_user.entries
  end

  def create
    entry = EntryCreator.call(entry_params, current_user)
    if entry.created?
      flash[:notice] = "New entry added"
    else
      flash[:alert] = entry.payload.errors.full_messages
    end
    redirect_to root_path
  end

  def show
    @entry = Entry.find_by(id: params[:id])
  end

  def edit
    @entry = Entry.find_by(id: params[:id])
  end

  def update
    @entry = Entry.find_by(id: params[:id])
    if @entry.update(entry_params)
      flash[:notice] = "Entry updated"
      redirect_to @entry
    else
      flash[:alert] = @entry.errors.full_messages
      render :edit
    end
  end

  def destroy
    @entry = Entry.find_by(id: params[:id])
    @entry.destroy
    flash[:notice] = "Entry deleted"
    redirect_to root_path
  end

  private

  def entry_params
    params.require(:entry).permit(:location, :note, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
    redirect_to entries_url if user_signed_in?
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", kind: "Google"
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"].except("extra") # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/_entry.html.haml
.row.g-0.rounded-3.shadow.mb-5.mx-3
  .col-md-3.h-100.overflow-hidden
    .m-1
      - if entry.photo.attached?
        = image_tag(entry.photo, class: 'img-fluid img-cover py-0 rounded-3')
      - else
        = image_tag('/images/road.jpg', class: 'img-fluid img-cover py-0 rounded-3')
  .col-md-9.px-3.py-1.min-h-100
    .fs-3.text-dark.mb-3.d-flex.flex-row.justify-content-between.w-100
      #{entry.location}, #{entry.created_at.strftime("%d.%m.%y")}
      .d-flex.flex-column.align-items-end
        .fs-3.text-dark.lh-1
          #{entry.temperature} &degC
        .fs-6.text-black-50
          #{entry.latitude} #{entry.longitude}
    .fs-6.min-h-50.overflow-hidden.pb-2
      #{entry.note[0..200]}......    
      .d-flex.flex-row.justify-content-end
        = link_to 'Read more', entry_path(entry), class: 'fs-5 link-secondary text-decoration-none'
    .d-flex.flex-row.justify-content-end
      = link_to "Edit", edit_entry_path(entry), class: 'btn btn-secondary btn-sm me-2 mb-4'
      = link_to "Delete", entry_path(entry), method: :delete, class: 'btn btn-secondary btn-sm ms-2 mb-4'
      

app/views/entries/_entry_form.html.haml
.shadow.mb-5.mt-4.p-3.rounded-3
  .mb-2.fs-1
    Add a new entry
  = form_for(:entry, url: entries_path) do |f|
    .form-group.mb-3
      = f.text_field :location, placeholder: 'Location', class: 'form-control'
    .form-group.mb-3
      = f.text_area :note, placeholder: 'Note', class: 'form-control input-field'
    .form-group.mb-3
      = f.file_field :photo, placeholder: 'Photo', class: 'form-control'
    .form-group
      = f.submit 'Add', class: 'btn btn-secondary'

app/views/entries/edit.html.haml
.shadow.p-3.rounded-3.mt-4
  .mb-2.fs-1
    Edit entry
  = form_for(:entry, url: entry_path(@entry), method: :patch ) do |f|
    .form-group.mb-3
      = f.text_field :location, placeholder: 'Location name', class: 'form-control'
    .form-group.mb-3
      = f.text_area :note, placeholder: 'Note', class: 'form-control input-field'
    .form-group.mb-3
      = f.file_field :photo, placeholder: 'Photo', class: 'form-control'
    .form-group
      = f.submit 'Update', class: 'btn btn-secondary'

app/views/entries/index.html.haml
= render 'entry_form'
= render @entries

app/views/entries/show.html.haml
.shadow.p-3.rounded-3.mt-4.mb-4
  .vh-40.overflow-hidden
    - if @entry.photo.attached?
      = image_tag(@entry.photo, class: 'img-fluid img-cover py-0 rounded-3')
    - else
      = image_tag('/images/road.jpg', class: 'img-fluid img-cover py-0 rounded-3')
  .min-vh-40
    .fs-3.text-dark.mb-3.d-flex.flex-row.justify-content-between.w-100.mt-3
      #{@entry.location}, #{@entry.created_at.strftime("%d.%m.%y")}
      .d-flex.flex-column.align-items-end
        .fs-3.text-dark.lh-1
          #{@entry.temperature} &degC
        .fs-6.text-black-50
          #{@entry.latitude} #{@entry.longitude}
    .fs-6.min-h-50.mx-4
      = @entry.note

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TravelLog
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/flash'
    = render 'shared/navbar' if current_user
    .container
      = yield

app/views/pages/welcome.html.haml
.container-fluid
  .full-height.d-flex.flex-column.justify-content-between.align-items-center
    %h1.mt-5.font-weight-bold Travel Log
    .p-2.mt-2.d-flex.flex-column.align-items-center
      = link_to 'Log in', new_user_session_url, class: 'btn btn-secondary btn-lg mt-3 mb-5'
    .p-2.d-flex.flex-column.align-items-center
      %p.fs-5.text-secondary Haven't got an account?
      %h2 Register now
      = link_to 'Sign up', new_user_registration_url, class: 'btn btn-secondary btn-lg mt-3'

app/views/shared/_flash.html.haml
- flash.each do |category, message| 
  %div{ class: "alert #{category == 'alert' ? 'alert-danger' : 'alert-success'}"}
    - if message.instance_of?(Array)
      - message.each do |m|
        %p #{m}
    - else
      = message

app/views/shared/_navbar.html.haml
.navbar.navbar-light.fixed-top
  .container-fluid
    .d-flex.flex-row-reverse.w-100
      .shadow
        .navbar-toggler{"aria-controls" => "offcanvasNavbar", "data-bs-target" => "#offcanvasNavbar", "data-bs-toggle" => "offcanvas", :type => "button"}
          .navbar-toggler-icon
    #offcanvasNavbar.offcanvas.offcanvas-end{"aria-labelledby" => "offcanvasNavbarLabel", :tabindex => "-1"}
      .offcanvas-header
        #offcanvasNavbarLabel.offcanvas-title.fs-2 Travel Log
        .btn-close.text-reset{"aria-label" => "Close", "data-bs-dismiss" => "offcanvas", :type => "button"}
      .offcanvas-body
        .navbar-nav.justify-content-end.flex-grow-1.pe-3.mb-5
          .nav-item
            = link_to 'Home', root_url, class: "nav-link fs-2"
        = link_to 'Logout', destroy_user_session_url, method: :delete, class: "btn btn-secondary"